/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.edu.Panels;

/**
 *
 * @author Admin
 */
public class TaiKhoanForm extends javax.swing.JPanel {

    /**
     * Creates new form TaiKhoanForm
     */
    public TaiKhoanForm() {
        initComponents();
         setOpaque(false);
         jFrame1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        tim = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MauDo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        form2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        from1 = new javax.swing.JButton();

        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tim.setBackground(new java.awt.Color(153, 0, 153));

        jLabel2.setText("Form1");

        javax.swing.GroupLayout timLayout = new javax.swing.GroupLayout(tim);
        tim.setLayout(timLayout);
        timLayout.setHorizontalGroup(
            timLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        timLayout.setVerticalGroup(
            timLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        add(tim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 520, 330));

        MauDo.setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setText("Form2");

        javax.swing.GroupLayout MauDoLayout = new javax.swing.GroupLayout(MauDo);
        MauDo.setLayout(MauDoLayout);
        MauDoLayout.setHorizontalGroup(
            MauDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MauDoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(184, 184, 184))
        );
        MauDoLayout.setVerticalGroup(
            MauDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MauDoLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(MauDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 520, 320));

        form2.setText("Form2");
        form2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form2ActionPerformed(evt);
            }
        });
        add(form2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabel1.setText("Tài Khoản");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 39, -1, -1));

        from1.setText("form1");
        from1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from1ActionPerformed(evt);
            }
        });
        add(from1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void from1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from1ActionPerformed
        // TODO add your handling code here:
        tim.setVisible(true);
        MauDo.setVisible(false);
    }//GEN-LAST:event_from1ActionPerformed

    private void form2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form2ActionPerformed
        // TODO add your handling code here:
        tim.setVisible(false);
        MauDo.setVisible(true);
    }//GEN-LAST:event_form2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MauDo;
    private javax.swing.JButton form2;
    private javax.swing.JButton from1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel tim;
    // End of variables declaration//GEN-END:variables
}
