/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.edu.Panels;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.TimerTask;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.HdrDocument;
import poly.edu.Model.KhuyenMai;
import poly.edu.Model.SanPhamChiTiet;
import poly.edu.service.SanPhamChiTietDao;
import poly.edu.service.VoucherService;

/**
 *
 * @author Admin
 */
public class VoucherForm extends javax.swing.JPanel {

    public static DefaultTableModel spAD;
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtmVC = new DefaultTableModel();
    DefaultTableModel dtmVCDelete = new DefaultTableModel();
    ArrayList<KhuyenMai> list = new ArrayList<>();
    VoucherService vs = new VoucherService();
    ArrayList<SanPhamChiTiet> listSPCT = new ArrayList<>();
    SanPhamChiTietDao spctd = new SanPhamChiTietDao();
    ArrayList<KhuyenMai> listKM = new ArrayList<>();
    LocalDate localDate = LocalDate.now();
    ZoneId zoneId = ZoneId.systemDefault();
    Date today = Date.from(localDate.atStartOfDay(zoneId).toInstant());
//    public void SpApKM() {
//        spAD.setRowCount(0);
//        int stt = 1;
//        for (SanPhamChiTiet spct : selectedData) {
//            spAD.addRow(new Object[]{spct.isDeleted(), stt++,
//                spct.getMaCTSP(), spct.getSp().getTen(), spct.getGia(), spct.getHang().getTen(),
//                spct.getMauSac().getTenMau(), spct.getSize().getSize(),
//                spct.getChatLieu().getTenChatLieu(), spct.getDeGiay().getTen()});
//        }
//    }

    /**
     * Creates new form VoucherForm
     */
    public VoucherForm() {
        initComponents();
        setOpaque(false);
        LoadDataToTable();
        spAD = (DefaultTableModel) tbApDung.getModel();
        dtmVC = (DefaultTableModel) tblVoucher.getModel();
        dtmVCDelete = (DefaultTableModel) tblVoucherDaXoa.getModel();
        // LoadDataToTableThietLap();
        listSPCT = spctd.selectAll();
        fillToTableALLSPCT(listSPCT);
        Random random1 = new Random();
        int Id = 100000 + random1.nextInt(900000);;
        String maKM = "KM" + Id;
        if (txtMaKM != null) {
            txtMaKM.setEnabled(false);
            txtMaKM.setText(maKM);
        }
        String maVC = "VC" + Id;
        if (txtMaVC != null) {
            txtMaVC.setEnabled(false);
            txtMaVC.setText(maVC);
        }
        fillToTableHoaDon();
        fillToTableHoaDonDaXoa();
        UpdateTrangThaiVoucher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTenVC = new javax.swing.JTextField();
        txtMaVC = new javax.swing.JTextField();
        cboLoaiVoucher = new javax.swing.JComboBox<>();
        txtGiaTriGiam = new javax.swing.JTextField();
        GiaTriToiThieu = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        btnThemVC = new javax.swing.JButton();
        btnSuaVC = new javax.swing.JButton();
        btnXoaVC = new javax.swing.JButton();
        btnLamMoiVC = new javax.swing.JButton();
        DateNgayBD = new com.toedter.calendar.JDateChooser();
        DateNgayKT = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        voucherTab = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblVoucherDaXoa = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        txtTenKM = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbApDung = new javax.swing.JTable();
        btnBoKhoiDanhSach = new javax.swing.JButton();
        ckbSelect = new javax.swing.JCheckBox();
        txtSearchSP = new javax.swing.JTextField();
        BtnApDungKM = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMucKM = new javax.swing.JTextField();
        cboHinhthucKM = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnNhanDuLieu = new javax.swing.JButton();
        thoigianbatdau = new com.toedter.calendar.JDateChooser();
        thoigianketthuc = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txtSearchDanhSach = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDanhSachKM = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDanhSachSanPham = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chương trình khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setToolTipText("");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin Voucher"));

        jLabel7.setText("Tên Voucher:");

        jLabel8.setText("Mã Voucher:");

        jLabel9.setText("Ngày bắt đầu:");

        jLabel10.setText("Ngày kết thúc:");

        jLabel11.setText("Loại voucher:");

        jLabel12.setText("Giá trị giảm:");

        jLabel13.setText("Giá trị đơn hàng tối thiểu:");

        jLabel14.setText("Số lượng:");

        cboLoaiVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảm theo số tiền", "Giảm theo %" }));

        btnThemVC.setBackground(new java.awt.Color(0, 204, 255));
        btnThemVC.setText("Thêm");
        btnThemVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVCActionPerformed(evt);
            }
        });

        btnSuaVC.setBackground(new java.awt.Color(0, 204, 255));
        btnSuaVC.setText("Sửa");
        btnSuaVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaVCActionPerformed(evt);
            }
        });

        btnXoaVC.setBackground(new java.awt.Color(0, 204, 255));
        btnXoaVC.setText("Xóa");
        btnXoaVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaVCActionPerformed(evt);
            }
        });

        btnLamMoiVC.setBackground(new java.awt.Color(0, 204, 255));
        btnLamMoiVC.setText("Làm mới");
        btnLamMoiVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiVCActionPerformed(evt);
            }
        });

        DateNgayBD.setDateFormatString("yyyy-MM-dd");

        DateNgayKT.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(txtTenVC, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaVC)
                            .addComponent(DateNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))))
                .addGap(85, 85, 85)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboLoaiVoucher, 0, 217, Short.MAX_VALUE)
                    .addComponent(txtGiaTriGiam)
                    .addComponent(GiaTriToiThieu)
                    .addComponent(txtSoLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemVC)
                    .addComponent(btnSuaVC)
                    .addComponent(btnXoaVC)
                    .addComponent(btnLamMoiVC))
                .addGap(95, 95, 95))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoiVC, btnSuaVC, btnThemVC, btnXoaVC});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(txtTenVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLoaiVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemVC))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(txtMaVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaTriGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuaVC))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(GiaTriToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaVC)))
                    .addComponent(DateNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel14)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLamMoiVC))
                    .addComponent(DateNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLamMoiVC, btnSuaVC, btnThemVC, btnXoaVC});

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách Voucher"));

        jLabel15.setText("Tìm kiếm:");

        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });

        voucherTab.setBackground(new java.awt.Color(255, 255, 255));

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Voucher", "Tên Voucher", "Ngày bắt đầu", "Ngày kết thúc", "Loại Voucher", "Giá trị giảm", "Số lượng", "Giá trị HĐ tối thiểu", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblVoucher);

        voucherTab.addTab("Voucher", jScrollPane4);

        tblVoucherDaXoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Voucher", "Tên Voucher", "Ngày bắt đầu", "Ngày kết thúc", "Loại Voucher", "Giá trị giảm", "Số lượng", "Giá trị HĐ tối thiểu", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoucherDaXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherDaXoaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblVoucherDaXoa);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        voucherTab.addTab("Voucher đã xóa", jPanel12);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(voucherTab)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(voucherTab, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Theo hóa đơn", jPanel8);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(0, 204, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaTrang.setBackground(new java.awt.Color(0, 204, 255));
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 204, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(0, 204, 255));
        btnHuy.setText("Hủy");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thiết lập khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        jLabel1.setText("Mã khuyến mãi");

        jLabel2.setText("Tên khuyến mãi");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm muốn áp dụng khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(240, 240, 240));

        tbApDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Select", "STT", "Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Hãng", "Màu sắc", "Size", "Chất liệu", "Đế giày"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbApDung);
        if (tbApDung.getColumnModel().getColumnCount() > 0) {
            tbApDung.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbApDung.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbApDung.getColumnModel().getColumn(7).setPreferredWidth(20);
        }

        btnBoKhoiDanhSach.setBackground(new java.awt.Color(0, 204, 255));
        btnBoKhoiDanhSach.setText("Bỏ khỏi danh sách");
        btnBoKhoiDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoKhoiDanhSachActionPerformed(evt);
            }
        });

        ckbSelect.setText("Select All");

        BtnApDungKM.setBackground(new java.awt.Color(0, 204, 255));
        BtnApDungKM.setText("Áp dụng khuyến mại");
        BtnApDungKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApDungKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbSelect)
                .addGap(23, 23, 23)
                .addComponent(btnBoKhoiDanhSach)
                .addGap(18, 18, 18)
                .addComponent(BtnApDungKM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBoKhoiDanhSach)
                    .addComponent(ckbSelect)
                    .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnApDungKM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jLabel3.setText("Mức giảm giá");

        jLabel4.setText("Hình thức giảm giá");

        cboHinhthucKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảm theo %", "Giảm theo số tiền" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenKM, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtMaKM))
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboHinhthucKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMucKM, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboHinhthucKM, txtMaKM, txtMucKM, txtTenKM});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMucKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cboHinhthucKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thời gian sử dụng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(240, 240, 240));

        btnNhanDuLieu.setBackground(new java.awt.Color(0, 204, 255));
        btnNhanDuLieu.setText("Lọc sản phẩm");
        btnNhanDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanDuLieuActionPerformed(evt);
            }
        });

        jLabel5.setText("Thời gian bắt đầu giảm giá:");

        jLabel6.setText("Thời gian kết thức giảm giá:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(thoigianbatdau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thoigianketthuc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addComponent(btnNhanDuLieu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(thoigianbatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnNhanDuLieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(thoigianketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        tabs.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(240, 240, 240));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang diễn ra", "Sắp diễn ra", "Hết hạn" }));

        tbDanhSachKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã khuyến mãi", "Tên khuyến mãi", "Hình thức giảm giá", "Giảm giá", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDanhSachKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhSachKMMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDanhSachKM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSearchDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Danh sách khuyến mãi", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(240, 240, 240));

        tbDanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Select", "STT", "Mã sản phẩm", "Tên sản phẩm", "Hãng", "Màu sắc", "Size", "Chất liệu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDanhSachSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhSachSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDanhSachSanPham);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Danh sách sản phẩm có trong khuyến mãi", jPanel5);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tabs)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHuy, btnSua, btnThem, btnXoaTrang});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHuy)
                            .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHuy, btnSua, btnThem, btnXoaTrang});

        jTabbedPane1.addTab("Theo sản phẩm", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanDuLieuActionPerformed
        // TODO add your handling code here:
        VoucherSanPham vcsp = new VoucherSanPham();
        vcsp.setVisible(true);
//        ArrayList<SanPhamChiTiet> listSPCT = new ArrayList<>();
//        SpApKM(listSPCT);
    }//GEN-LAST:event_btnNhanDuLieuActionPerformed

    private void tbDanhSachKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhSachKMMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            tabs.setSelectedIndex(1);
            LoadDataToTableTheoMaKM();
        } else if (evt.getClickCount() == 1) {
            showDataKm();
        }
    }//GEN-LAST:event_tbDanhSachKMMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        updateKM();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbDanhSachSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhSachSanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDanhSachSanPhamMouseClicked

    private void btnBoKhoiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoKhoiDanhSachActionPerformed
        // TODO add your handling code here:
//        System.out.println(getIDSPCTTich());
    }//GEN-LAST:event_btnBoKhoiDanhSachActionPerformed

    private void BtnApDungKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApDungKMActionPerformed
        // TODO add your handling code here:
        ArrayList<SanPhamChiTiet> selectedKM = new ArrayList<>();
        getIDSPCTTich(selectedKM);


    }//GEN-LAST:event_BtnApDungKMActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insertKM();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        // TODO add your handling code here:
        showDataVoucher();
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void btnThemVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVCActionPerformed
        // TODO add your handling code here:
        insertVoucher();
    }//GEN-LAST:event_btnThemVCActionPerformed

    private void btnSuaVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaVCActionPerformed
        // TODO add your handling code here:
        updateVoucher();
    }//GEN-LAST:event_btnSuaVCActionPerformed

    private void btnLamMoiVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiVCActionPerformed
        // TODO add your handling code here:
        lamMoiVoucher();
    }//GEN-LAST:event_btnLamMoiVCActionPerformed

    private void tblVoucherDaXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherDaXoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVoucherDaXoaMouseClicked

    private void btnXoaVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaVCActionPerformed
        // TODO add your handling code here:
        xoaVoucher();
    }//GEN-LAST:event_btnXoaVCActionPerformed

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
        String keyword1 = txtTK.getText();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dtmVC);
        tblVoucher.setRowSorter(sorter);

        if (keyword1.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword1));
        }
    }//GEN-LAST:event_txtTKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnApDungKM;
    private com.toedter.calendar.JDateChooser DateNgayBD;
    private com.toedter.calendar.JDateChooser DateNgayKT;
    private javax.swing.JTextField GiaTriToiThieu;
    private javax.swing.JButton btnBoKhoiDanhSach;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoiVC;
    private javax.swing.JButton btnNhanDuLieu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaVC;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemVC;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JButton btnXoaVC;
    private javax.swing.JComboBox<String> cboHinhthucKM;
    private javax.swing.JComboBox<String> cboLoaiVoucher;
    private javax.swing.JCheckBox ckbSelect;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbApDung;
    private javax.swing.JTable tbDanhSachKM;
    private javax.swing.JTable tbDanhSachSanPham;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTable tblVoucherDaXoa;
    private com.toedter.calendar.JDateChooser thoigianbatdau;
    private com.toedter.calendar.JDateChooser thoigianketthuc;
    private javax.swing.JTextField txtGiaTriGiam;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtMaVC;
    private javax.swing.JTextField txtMucKM;
    private javax.swing.JTextField txtSearchDanhSach;
    private javax.swing.JTextField txtSearchSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTenKM;
    private javax.swing.JTextField txtTenVC;
    private javax.swing.JTabbedPane voucherTab;
    // End of variables declaration//GEN-END:variables
 public void LoadDataToTable() {

        dtm = (DefaultTableModel) tbDanhSachKM.getModel();

        dtm.setRowCount(0);
        list = vs.getAllKhuyenMai();
        int stt = 1;
        for (KhuyenMai km : list) {
            dtm.addRow(new Object[]{
                stt++, km.getMaKM(), km.getTenVC(), km.getHinhThucGiamGia(), km.getMucGiamGia(), km.getNgayBatDau(), km.getNgayKetThuc(), km.getSoLuong(),});
        }

    }

    public void LoadDataToTableTheoMaKM() {

        dtm = (DefaultTableModel) tbDanhSachSanPham.getModel();

        dtm.setRowCount(0);
        int row = tbDanhSachKM.getSelectedRow();
        String ma = tbDanhSachKM.getValueAt(row, 1).toString();
        list = vs.getAllSPCTmaKM(ma);
        int stt = 1;
        for (KhuyenMai km : list) {
            dtm.addRow(new Object[]{
                km.isDeleted(), stt++, km.getMaSPCT(), km.getTenSP(), km.getTenHang(), km.getMauSac(),
                km.getSize(), km.getChatLieu()});
        }

    }

    public void ShowTableTheoMaKM() {

        dtm = (DefaultTableModel) tbApDung.getModel();

        dtm.setRowCount(0);
        int row = tbDanhSachKM.getSelectedRow();
        String ma = tbDanhSachKM.getValueAt(row, 1).toString();
        list = vs.getAllSPCTmaKM(ma);
        int stt = 1;
        for (KhuyenMai km : list) {
            dtm.addRow(new Object[]{
                km.isDeleted(), stt++, km.getMaSPCT(), km.getTenSP(), km.getGiaBan(), km.getTenHang(), km.getMauSac(),
                km.getSize(), km.getChatLieu(), km.getDeGiay()});
        }

    }

//    public void SpApKM(ArrayList<SanPhamChiTiet> listSPCT) {
//        spAD.setRowCount(0);
//        int stt = 1;
//        for (SanPhamChiTiet spct : listSPCT) {
//            spAD.addRow(new Object[]{spct.isDeleted(), stt++,
//                spct.getMaCTSP(), spct.getSp().getTen(), spct.getGia(), spct.getHang().getTen(),
//                spct.getMauSac().getTenMau(), spct.getSize().getSize(),
//                spct.getChatLieu().getTenChatLieu(), spct.getDeGiay().getTen()});
//        }
//
//    }
    void showDataKm() {
        int rowKM = tbDanhSachKM.getSelectedRow();
        txtMaKM.setText(tbDanhSachKM.getValueAt(rowKM, 1).toString());
        txtTenKM.setText(tbDanhSachKM.getValueAt(rowKM, 2).toString());
        txtMucKM.setText(tbDanhSachKM.getValueAt(rowKM, 4).toString());
        cboHinhthucKM.setSelectedItem(tbDanhSachKM.getValueAt(rowKM, 3));
        thoigianbatdau.setDate((Date) tbDanhSachKM.getValueAt(rowKM, 5));
        thoigianketthuc.setDate((Date) tbDanhSachKM.getValueAt(rowKM, 6));
        ShowTableTheoMaKM();
    }

    KhuyenMai checkformKhuyenMai() {

        KhuyenMai km = new KhuyenMai();
        String maKM = txtMaKM.getText();
        String tenKM = txtTenKM.getText();
        String muckm = txtMucKM.getText();
        String htKM = cboHinhthucKM.getSelectedItem().toString();
        Date batdau = thoigianbatdau.getDate();
        Date ketThuc = thoigianketthuc.getDate();
        if (maKM.isEmpty() || tenKM.isEmpty() || muckm.isEmpty() || batdau == null || ketThuc == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!");
            return null;
        }
        km.setMaKM(maKM);
        km.setTenVC(tenKM);
        km.setMucGiamGia(muckm);
        km.setHinhThucGiamGia(htKM);
        km.setNgayBatDau(batdau);
        km.setNgayKetThuc(ketThuc);
        km.setNguoiTao("NV001");
        km.setNguoiSua("NV001");
        return km;
    }

    void updateKM() {
        KhuyenMai km = checkformKhuyenMai();
        if (km == null) {
            return;
        }
        try {
            vs.updateKM(km);
            LoadDataToTable();
            JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại!");
        }
    }

    void insertKM() {
        KhuyenMai km = checkformKhuyenMai();
        String mucGiam = txtMucKM.getText();
        if (km == null) {
            return;
        }

        try {
            ArrayList<SanPhamChiTiet> selectedKM = new ArrayList<>();
            getIDSPCTTich(selectedKM);

            System.out.println(selectedKM);
            for (SanPhamChiTiet spct : selectedKM) {
                km.setId_SPCT(spct.getId());
                if (cboHinhthucKM.getSelectedItem().equals("Giảm theo %")) {
                    km.setSoTienGiam(spct.getGia() * Integer.parseInt(mucGiam) / 100);
                } else {
                    km.setSoTienGiam(Integer.parseInt(txtMucKM.getText()));
                }
            }
            km.setTrangThai("Thành công");
            km.setNguoiSua("NV001");
            km.setNguoiTao("NV001");
            km.setDeleted(true);
            vs.insertKM(km);
            JOptionPane.showMessageDialog(null, "Thành công!");
            LoadDataToTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Thất bại");
        }
    }

    private void fillToTableALLSPCT(ArrayList<SanPhamChiTiet> listspct) {
        dtm = (DefaultTableModel) tbApDung.getModel();
        dtm.setRowCount(0);
        listspct = spctd.selectAllKCoKM();
        int size = listspct.size();
        for (int i = 0; i < size; i++) {
            SanPhamChiTiet spct = listspct.get(i);
            Object[] rowData = spct.toDataRowKM(i + 1);
            dtm.addRow(rowData);
        }

    }

    public void getIDSPCTTich(ArrayList<SanPhamChiTiet> selectedKM) {
        dtm = (DefaultTableModel) tbApDung.getModel();
        listSPCT = spctd.selectAllKCoKM();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            boolean tick = (Boolean) dtm.getValueAt(i, 0);

            if (tick) {
                SanPhamChiTiet spct = listSPCT.get(i);
                selectedKM.add(spct);
                System.out.println(spct.getId());
                System.out.println(spct.getMaCTSP());

            }
        }

        // Cập nhật lại bảng tbApDung với danh sách selectedListSPCT
        dtm.setRowCount(0);
        int size = selectedKM.size();
        for (int i = 0; i < size; i++) {
            SanPhamChiTiet spct = selectedKM.get(i);
            Object[] rowData = spct.toDataRowKM(i + 1);
            dtm.addRow(rowData);
        }
    }

    void clearForm() {
        txtMaKM.setText("");
        txtTenKM.setText("");
        txtMucKM.setText("");
        thoigianbatdau.setDateFormatString("");
        thoigianketthuc.setDateFormatString("");
        fillToTableALLSPCT(listSPCT);
    }

    //Giảm giá theo hóa đơn
    ///
    ///
    void fillToTableHoaDon() {
        dtmVC.setRowCount(0);
        listKM = vs.getAllVoucher();
        int stt = 1;
        for (KhuyenMai km : listKM) {
            dtmVC.addRow(new Object[]{
                stt++, km.getMaKM(), km.getTenVC(), km.getNgayBatDau(), km.getNgayKetThuc(), km.getHinhThucGiamGia(), km.getMucGiamGia(), km.getSoLuong(), km.getGiaTriDHToiThieu(),
                km.getTrangThai()
            });
        }
    }

    void fillToTableHoaDonDaXoa() {
        dtmVCDelete.setRowCount(0);
        listKM = vs.getAllVoucherDaXoa();
        int stt = 1;
        for (KhuyenMai km : listKM) {
            dtmVCDelete.addRow(new Object[]{
                stt++, km.getMaKM(), km.getTenVC(), km.getNgayBatDau(), km.getNgayKetThuc(), km.getHinhThucGiamGia(), km.getMucGiamGia(), km.getSoLuong(), km.getGiaTriDHToiThieu(),
                km.getTrangThai()
            });
        }
    }

    void showDataVoucher() {
        int row = tblVoucher.getSelectedRow();
        txtTenVC.setText(tblVoucher.getValueAt(row, 2).toString());
        txtMaVC.setText(tblVoucher.getValueAt(row, 1).toString());
        DateNgayBD.setDate((Date) tblVoucher.getValueAt(row, 3));
        DateNgayKT.setDate((Date) tblVoucher.getValueAt(row, 4));
        cboLoaiVoucher.setSelectedItem(tblVoucher.getValueAt(row, 5).toString());
        txtGiaTriGiam.setText(tblVoucher.getValueAt(row, 6).toString());
        GiaTriToiThieu.setText(tblVoucher.getValueAt(row, 7).toString());
        txtSoLuong.setText(tblVoucher.getValueAt(row, 8).toString());
    }

    KhuyenMai checkFormVC() {
        KhuyenMai km = new KhuyenMai();

        String tenVC = txtTenVC.getText();
        String maVC = txtMaVC.getText();
        Date ngayBD = DateNgayBD.getDate();
        Date ngayKT = DateNgayKT.getDate();
        String loaiVC = cboLoaiVoucher.getSelectedItem().toString();
        String giaTriGiam = txtGiaTriGiam.getText();
        String giaTriDonhangToiThieu = GiaTriToiThieu.getText();
        String sl = txtSoLuong.getText();
        if (tenVC.isEmpty() || maVC.isEmpty() || ngayBD.equals("") || ngayKT.equals("") || loaiVC.isEmpty() || giaTriGiam.isEmpty() || giaTriDonhangToiThieu.isEmpty() || sl.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!");
            return null;
        }
//        if (ngayBD.before(today) && ngayKT.before(today) || ngayBD.after(ngayKT) || ngayBD.before(today) || ngayKT.before(today)) {
//            JOptionPane.showMessageDialog(null, "Nhập sai ngày bắt đầu và ngày kết thúc!");
//            return null;
//        }

        try {
            int giatriGiamInt = Integer.parseInt(giaTriGiam);
            int giatriDHInt = Integer.parseInt(giaTriDonhangToiThieu);
            int slInt = Integer.parseInt(sl);
            if (giatriGiamInt <= 0 || giatriDHInt <= 0 || slInt <= 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập số nguyên dương: giá trị giảm, Giá trị đơn hàng, số lượng");
            } else {
                km.setTenVC(tenVC);
                km.setMaKM(maVC);
                km.setNgayBatDau(ngayBD);
                km.setNgayKetThuc(ngayKT);
                km.setHinhThucGiamGia(loaiVC);
                km.setMucGiamGia(giaTriGiam);
                km.setGiaTriDHToiThieu(giatriDHInt);
                km.setSoLuong(slInt);
                km.setNguoiSua("NV001");
                km.setNguoiTao("NV001");

//                if ( ngayBD.equals(today)) {
//                    km.setTrangThai("Đang diễn ra");
//                }
                
                if (ngayBD.before(today) && ngayKT.after(today) || ngayBD.equals(today) && ngayKT.equals(today) || ngayBD.equals(today) && ngayKT.after(today)) {
                    km.setTrangThai("Đang diễn ra");
                } else if (ngayBD.after(today) && ngayKT.after(today)) {
                    km.setTrangThai("Sắp diễn ra");
                } else {
                    km.setTrangThai("Đã hết hạn");
                }
                return km;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số nguyên dương: giá trị giảm, Giá trị đơn hàng, số lượng");
        }
        return km;
    }

    void insertVoucher() {
        KhuyenMai km = checkFormVC();
        if (km == null) {
            return;
        }
        int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thêm?", "Trả lời", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                vs.insertVoucher(km);
                JOptionPane.showMessageDialog(null, "Thành công!");
                fillToTableHoaDon();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Thất bại");
            }
        } else {
            return;
        }
    }

    void updateVoucher() {
        int row = tblVoucher.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần sửa!");
            return;
        }
        KhuyenMai km = checkFormVC();
        if (km == null) {
            return;
        }

        km.setMaKM(tblVoucher.getValueAt(row, 1).toString());
        int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa?", "Trả lời", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                vs.updateVoucher(km);
                JOptionPane.showMessageDialog(null, "Thành công!");
                fillToTableHoaDon();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Thất bại");
            }
        } else {
            return;
        }
    }

    void lamMoiVoucher() {
        txtTenVC.setText("");
        txtMaVC.setText("");
//        DateNgayBD.setDate(" ");
//        DateNgayKT.setDateFormatString(" ");
        txtGiaTriGiam.setText("");
        GiaTriToiThieu.setText("");
        txtSoLuong.setText("");
        Random random1 = new Random();
        int Id = 100000 + random1.nextInt(900000);;
        String maVC = "VC" + Id;
        if (txtMaVC != null) {
            txtMaVC.setEnabled(false);
            txtMaVC.setText(maVC);
        }
    }

    void xoaVoucher() {
        int row = tblVoucher.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần Sửa !");
            return;
        }
        int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa?", "Trả lời", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {

                KhuyenMai km = new KhuyenMai();
                String maVC = tblVoucher.getValueAt(row, 1).toString();
                km.setMaKM(maVC);
                km.setTrangThai("Voucher đã xóa");
                vs.deleteVoucher(km);
                JOptionPane.showMessageDialog(null, "Thành công !");
                fillToTableHoaDon();
                voucherTab.setSelectedIndex(1);
                fillToTableHoaDonDaXoa();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Thất bại");
            }
        } else {
            return;
        }
    }

    void UpdateTrangThaiVoucher() {

        listKM = vs.getAllVoucher();
        for (KhuyenMai km : listKM) {
            Date ngayBD = km.getNgayBatDau();
            Date ngayKT = km.getNgayKetThuc();
            if (ngayBD.before(today) && ngayKT.after(today) || ngayBD.equals(today) && ngayKT.equals(today) || ngayBD.equals(today) && ngayKT.after(today)) {
                km.setTrangThai("Đang diễn ra");
            } else if (ngayBD.after(today) && ngayKT.after(today)) {
                km.setTrangThai("Sắp diễn ra");
            } else {
                km.setTrangThai("Đã hết hạn");
            }
        }

        fillToTableHoaDon();
    }

}
